package cicosy.templete.domain;

public enum ContractType {
    SERVICE_AGREEMENT,
    EMPLOYMENT_CONTRACT,
    LEASE_AGREEMENT,
    PURCHASE_AGREEMENT,
    LICENSING_AGREEMENT,
    MAINTENANCE_CONTRACT,
    CONSULTING_AGREEMENT,
    PARTNERSHIP_AGREEMENT,
    CONFIDENTIALITY_AGREEMENT,
    OTHER
}